#!/usr/bin/env python3
"""
Submit a SLURM job to run tau_vtx hyperparameter tuning scan.

This script scans tau_vtx values across (Nrays, Energy) combinations to find
the optimal tau_vtx parametrization for the vertex loss function.

The scan grid covers:
- Nrays: [50k, 150k, 250k]
- Energy: [500, 1000, 1500] MeV
- tau_vtx: Various values per (Nrays, Energy) combination

Results are saved to CSV with bootstrap confidence intervals for 68% percentiles.
Use good_notebooks/analyze_tau_scan.ipynb to derive the parametrization from results.

Usage:
    python submit_tau_hyperparameter_tuning_job.py --output OUTPUT_DIR [--n-events N] [--submit]

Example:
    python submit_tau_hyperparameter_tuning_job.py --output ../output/tau_scan --submit
"""

import argparse
import subprocess
from pathlib import Path
from datetime import datetime


# =============================================================================
# SCAN PARAMETERS
# =============================================================================
# Format: (nrays, energy_MeV, [tau_vtx values])
# This grid covers the full parameter space for tau_vtx optimization
SCAN_GRID = [
    # Nrays=50k
    (50_000,  500,  [0.10, 0.12, 0.15, 0.18, 0.25]),
    (50_000,  1000, [0.20, 0.25, 0.30, 0.35]),
    (50_000,  1500, [0.30, 0.35, 0.40, 0.45, 0.50]),
    # Nrays=150k
    (150_000, 500,  [0.15, 0.20, 0.25, 0.30]),
    (150_000, 1000, [0.30, 0.35, 0.40, 0.45]),
    (150_000, 1500, [0.35, 0.40, 0.45, 0.50]),
    # Nrays=250k
    (250_000, 500,  [0.30, 0.35, 0.40, 0.45, 0.50]),
    (250_000, 1000, [0.45, 0.50, 0.55, 0.60]),
    (250_000, 1500, [0.55, 0.65, 0.70, 0.75, 0.80]),
]


def count_combinations():
    """Count total number of (nrays, energy, tau) combinations."""
    return sum(len(tau_list) for _, _, tau_list in SCAN_GRID)


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description='Submit SLURM job for tau_vtx hyperparameter tuning'
    )
    parser.add_argument(
        '--output',
        type=str,
        required=True,
        help='Directory where results will be saved'
    )
    parser.add_argument(
        '--n-events',
        type=int,
        default=50,
        help='Number of events per parameter combination (default: 50)'
    )
    parser.add_argument(
        '--job-name',
        type=str,
        default='tau_scan',
        help='Name for the SLURM job (default: tau_scan)'
    )
    parser.add_argument(
        '--submit',
        action='store_true',
        help='Actually submit the job (default: just generate script)'
    )
    parser.add_argument(
        '--partition',
        type=str,
        default='ampere',
        help='SLURM partition (default: ampere)'
    )
    parser.add_argument(
        '--account',
        type=str,
        default='mli:cider-ml',
        help='SLURM account (default: mli:cider-ml)'
    )
    parser.add_argument(
        '--time',
        type=str,
        default='24:00:00',
        help='Job time limit HH:MM:SS (default: 24:00:00)'
    )
    return parser.parse_args()


def generate_run_script(project_root):
    """Generate the Python run script content."""

    # Convert SCAN_GRID to string representation
    scan_grid_str = "[\n"
    for nrays, energy, tau_list in SCAN_GRID:
        scan_grid_str += f"    ({nrays:_}, {energy}, {tau_list}),\n"
    scan_grid_str += "]"

    run_script = f'''#!/usr/bin/env python
"""
Run tau_vtx hyperparameter scan.
Auto-generated by submit_tau_hyperparameter_tuning_job.py
"""

import argparse
import csv
import os
import glob
from datetime import datetime
from tqdm import tqdm

import jax
import jax.numpy as jnp
import numpy as np
import uproot
import optax
from jax import jit, value_and_grad
from jax.scipy.special import gammaln

from lucid.geometry import generate_detector
from lucid.sources.event_io import read_photon_data_from_photonsim
from lucid.simulation import setup_event_simulator
from lucid.utils import load_range_params, check_track_endpoint_in_detector
from lucid.detector_params import ParticleParams
from lucid.wavelength import DEFAULT_WAVELENGTH_NM
from lucid.optimization.grid_search import (
    load_optimization_config,
    get_detector_bounds,
    hierarchical_position_grid_search
)
from lucid.optimization.utils.functions import (
    cartesian_to_spherical,
    spherical_to_cartesian,
)
from lucid.losses import first_arrival_nll


SCAN_GRID = {scan_grid_str}

ENERGY_BASE_PATH = '/sdf/data/neutrino/cjesus/photonsim_output/water/monoenergetic/event_by_event/mu-/'
PHYSICS_CONFIG = str(project_root / 'config' / 'SK_physics_config.json')
GEOM_CONFIG = str(project_root / 'config' / 'SK_geom_config.json')
OPT_CONFIG = str(project_root / 's3df_jobs' / 'nrays_config' / 'opt_config_5.json')

TAU_TIME = 0.15
TEMPERATURE = 0.1
K = 7
N_BOOTSTRAP = 100


def bootstrap_percentile_ci(data, percentile=68, n_bootstrap=N_BOOTSTRAP, ci_level=68, rng=None):
    data = np.asarray(data)
    n = data.size
    if n == 0:
        return None
    if rng is None:
        rng = np.random.default_rng()
    boots = np.empty(n_bootstrap, dtype=float)
    for i in range(n_bootstrap):
        sample = rng.choice(data, size=n, replace=True)
        boots[i] = np.percentile(sample, percentile)
    alpha = (100 - ci_level) / 2
    ci_lower = np.percentile(boots, alpha)
    ci_upper = np.percentile(boots, 100 - alpha)
    est = np.percentile(data, percentile)
    return {{"estimate": float(est), "ci_lower": float(ci_lower),
            "ci_upper": float(ci_upper), "std_error": float(np.std(boots, ddof=1))}}


def poisson_nll(true, pred, eps=1e-8):
    nll = pred - true * jnp.log(pred + eps) + gammaln(true + 1.0)
    return jnp.sum(nll) / (jnp.sum(true) + eps)


def softplus(x):
    return jnp.log1p(jnp.exp(-jnp.abs(x))) + jnp.maximum(x, 0.)


def smooth_pinball(r, tau=0.1, sigma=0.5):
    pos = softplus(r / sigma) * sigma
    neg = softplus(-r / sigma) * sigma
    return tau * pos + (1.0 - tau) * neg


@jit
def origin_time_loss_configurable(origin, detector_positions, true_times, true_q, t0,
                                   tau_vtx, photosensor_radius=0.25, c_medium=(0.299792/1.33)):
    d = jnp.linalg.norm(detector_positions - origin[None, :], axis=1)
    expected = (d - photosensor_radius) / c_medium
    r = true_times - expected - t0
    w = jnp.where(true_q > 0., 1., 0.)
    wsum = jnp.sum(w) + 1e-8
    main = jnp.sum(w * smooth_pinball(r, tau=tau_vtx, sigma=0.25)) / wsum
    return main


def create_combined_loss_function(prediction_simulator, num_detectors,
                                  tau_time, tau_vtx, hit_detector_positions):
    @jit
    def combined_product_loss(params, observed_times, observed_counts, key):
        position = params[:3]
        t0 = params[3]
        theta = params[4]
        phi = params[5]
        energy = params[6]

        track = ParticleParams(energy=energy, position=position, theta=theta, phi=phi, t0=jnp.array(0.0))
        log_w, flat_times, flat_indices, total_charge = prediction_simulator(track, key)

        charge_loss = poisson_nll(observed_counts, total_charge)
        t_obs_shifted = observed_times - t0

        time_nll = first_arrival_nll(
            log_w, flat_times, flat_indices,
            t_obs_shifted, tau_time, num_detectors)

        hit_mask = observed_counts > 0
        n_hit = jnp.sum(hit_mask) + 1e-8
        time_loss = jnp.sum(jnp.where(hit_mask, time_nll, 0.0)) / n_hit

        vertex_loss_val = origin_time_loss_configurable(
            jax.lax.stop_gradient(position), hit_detector_positions, observed_times,
            observed_counts, t0, tau_vtx=tau_vtx)

        c = charge_loss
        t = time_loss
        v = vertex_loss_val
        s = 0.

        combined = jnp.sqrt((c + s) * (t + s) * (v + s))\\
            + jnp.sqrt((c + s) * jax.lax.stop_gradient((t + s) * (v + s)))\\
            + jnp.sqrt((v + s) * jax.lax.stop_gradient((t + s) * (c + s)))

        sqrt_ct = jnp.sqrt(c * t)

        return combined, (charge_loss, time_loss, vertex_loss_val, sqrt_ct)

    combined_grad_fn = jit(value_and_grad(combined_product_loss, has_aux=True))
    return combined_grad_fn, combined_product_loss


def generate_event_data(event_idx, random_key, data_dir, data_simulator,
                        detector_bounds, detector_points, fraction=0.9):
    root_files = sorted(glob.glob(os.path.join(data_dir, "*.root")))
    if not root_files:
        raise ValueError(f"No .root files found in directory: {{data_dir}}")

    file_select_key, random_key = jax.random.split(random_key)
    file_idx = jax.random.randint(file_select_key, shape=(), minval=0, maxval=len(root_files))
    data_file = root_files[int(file_idx)]

    with uproot.open(data_file) as file:
        tree = file['OpticalPhotons']
        n_entries = tree.num_entries

    entry_idx = event_idx % n_entries
    photon_data = read_photon_data_from_photonsim(data_file, entry_idx)

    photon_origins = photon_data['photon_origins']
    photon_directions = photon_data['photon_directions']
    photon_times = photon_data['photon_times']
    N = len(photon_origins)

    padding_size = max(0, 1_000_000 - N)
    photon_data['photon_origins'] = jnp.pad(photon_origins, ((0, padding_size), (0, 0)),
                                             mode='constant', constant_values=0)

    default_direction = jnp.array([0.0, 0.0, 1.0])
    padding_directions = jnp.tile(default_direction, (padding_size, 1))
    if padding_size > 0:
        photon_data['photon_directions'] = jnp.concatenate([photon_directions, padding_directions], axis=0)
    else:
        photon_data['photon_directions'] = photon_directions

    photon_data['photon_times'] = jnp.pad(photon_times, (0, padding_size),
                                          mode='constant', constant_values=0)

    if 'wavelengths' in photon_data:
        photon_data['wavelengths'] = jnp.pad(
            photon_data['wavelengths'], (0, padding_size),
            mode='constant', constant_values=DEFAULT_WAVELENGTH_NM)

    photon_data['N'] = N

    key = random_key
    DETECTOR_R = detector_bounds['r']
    DETECTOR_H = detector_bounds['H']

    r_vert = jax.random.uniform(key, shape=(), minval=0, maxval=DETECTOR_R * fraction)
    key, _ = jax.random.split(key)
    theta = jax.random.uniform(key, shape=(), minval=0, maxval=2*jnp.pi)
    key, _ = jax.random.split(key)
    z_vert = jax.random.uniform(key, shape=(), minval=-DETECTOR_H/2 * fraction,
                                maxval=DETECTOR_H/2 * fraction)
    true_position = jnp.array([r_vert * jnp.cos(theta), r_vert * jnp.sin(theta), z_vert])

    key, _ = jax.random.split(key)
    phi = jax.random.uniform(key, shape=(), minval=0, maxval=2*jnp.pi)
    key, _ = jax.random.split(key)
    cos_theta = jax.random.uniform(key, shape=(), minval=-1, maxval=1)
    sin_theta = jnp.sqrt(1 - cos_theta**2)
    true_direction = jnp.array([sin_theta * jnp.cos(phi), sin_theta * jnp.sin(phi), cos_theta])

    true_energy = photon_data['energy']
    TRUE_T0 = jax.random.uniform(key, shape=(), minval=-15.0, maxval=15.0)

    true_track = ParticleParams.from_cartesian(
        energy=true_energy, position=true_position, direction=true_direction, t0=0.0
    )

    original_direction = jnp.array([0.0, 0.0, 1.0])
    true_direction_norm = true_direction / (jnp.linalg.norm(true_direction) + 1e-8)
    rotation_axis = jnp.cross(original_direction, true_direction_norm)
    axis_norm = jnp.linalg.norm(rotation_axis)
    rotation_axis = jnp.where(
        axis_norm < 1e-6,
        jnp.array([1.0, 0.0, 0.0]),
        rotation_axis / (axis_norm + 1e-8)
    )
    rotation_angle = jnp.arccos(jnp.clip(
        jnp.dot(original_direction, true_direction_norm), -1.0, 1.0
    ))

    photon_data['rotation_axis'] = rotation_axis
    photon_data['rotation_angle'] = rotation_angle
    photon_data['apply_rotation'] = jnp.array(True)
    photon_data['apply_translation'] = jnp.array(True)
    photon_data['translation_vector'] = true_position

    key, _ = jax.random.split(key)
    true_data = jax.lax.stop_gradient(data_simulator(true_track, key, photon_data))

    hit_counts, hit_times_raw = true_data
    hit_times = hit_times_raw + TRUE_T0

    return {{
        'event_idx': event_idx,
        'entry_idx': entry_idx,
        'true_energy': float(true_energy),
        'true_position': np.array(true_position),
        'true_direction': np.array(true_direction),
        'TRUE_T0': float(TRUE_T0),
        'true_data': true_data,
        'hit_times': hit_times,
        'hit_counts': hit_counts,
        'photon_data': photon_data
    }}


def run_stage_1_position_search(hit_detector_positions, observed_times, observed_counts,
                                 true_position, TRUE_T0, initial_t0, detector_bounds, config):
    pos_results = hierarchical_position_grid_search(
        hit_detector_positions, observed_times, observed_counts,
        true_position, TRUE_T0, initial_t0, detector_bounds,
        n_div=config['position_grid_search']['pos_n_div'],
        t0_n_div=config['position_grid_search']['t0_n_div'],
        levels=config['position_grid_search']['pos_levels'],
        fraction=config['position_grid_search']['pos_fraction'],
        t0_min=config['position_grid_search']['t0_min'],
        t0_max=config['position_grid_search']['t0_max'],
        min_L=config['position_grid_search']['pos_min_L'],
        verbosity=0
    )
    return pos_results


def run_stage_2_direction_search(optimal_position, optimal_t0, energy_guess,
                                  observed_counts, true_direction, config, prediction_simulator):
    levels = config['cone_direction_search']['cone_levels']
    initial_div = config['cone_direction_search']['cone_initial_div']
    max_angle_deg = config['cone_direction_search']['cone_max_angle_deg']
    reduction = config['cone_direction_search']['cone_reduction']

    best_direction = np.array([0., 0., 1.])
    best_theta = 0.
    best_phi = 0.
    best_loss = float('inf')

    cone_key = jax.random.PRNGKey(42)
    current_max_angle = np.radians(max_angle_deg)

    def rotation_matrix_from_vectors(vec1, vec2):
        a = vec1 / (np.linalg.norm(vec1) + 1e-8)
        b = vec2 / (np.linalg.norm(vec2) + 1e-8)
        v = np.cross(a, b)
        c = np.dot(a, b)
        if np.linalg.norm(v) < 1e-8:
            if c > 0:
                return np.eye(3)
            else:
                perp = np.array([1., 0., 0.]) if abs(a[0]) < 0.9 else np.array([0., 1., 0.])
                perp = perp - np.dot(perp, a) * a
                perp = perp / (np.linalg.norm(perp) + 1e-8)
                return 2 * np.outer(perp, perp) - np.eye(3)
        s = np.linalg.norm(v)
        kmat = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
        return np.eye(3) + kmat + kmat @ kmat * ((1 - c) / (s * s + 1e-8))

    for level in range(levels):
        n_theta = initial_div
        n_phi = initial_div * 2

        if level == 0:
            for i in range(n_theta):
                theta_val = np.pi * (i / max(n_theta - 1, 1))
                for j in range(n_phi):
                    phi_val = 2 * np.pi * (j / n_phi)
                    direction = spherical_to_cartesian(theta_val, phi_val)
                    track = ParticleParams(energy=energy_guess, position=optimal_position,
                                           theta=theta_val, phi=phi_val, t0=optimal_t0)
                    _, _, _, total_charge = prediction_simulator(track, cone_key)
                    loss = poisson_nll(observed_counts, total_charge)
                    if loss < best_loss:
                        best_loss = loss
                        best_direction = np.array(direction)
                        best_theta = theta_val
                        best_phi = phi_val
        else:
            z_axis = np.array([0., 0., 1.])
            R = rotation_matrix_from_vectors(z_axis, best_direction)
            for i in range(n_theta):
                cone_theta = current_max_angle * (i / max(n_theta - 1, 1))
                for j in range(n_phi):
                    cone_phi = 2 * np.pi * (j / n_phi)
                    local_dir = np.array([
                        np.sin(cone_theta) * np.cos(cone_phi),
                        np.sin(cone_theta) * np.sin(cone_phi),
                        np.cos(cone_theta)
                    ])
                    direction = R @ local_dir
                    direction = direction / (np.linalg.norm(direction) + 1e-8)
                    theta_val, phi_val = cartesian_to_spherical(direction)
                    track = ParticleParams(energy=energy_guess, position=optimal_position,
                                           theta=theta_val, phi=phi_val, t0=optimal_t0)
                    _, _, _, total_charge = prediction_simulator(track, cone_key)
                    loss = poisson_nll(observed_counts, total_charge)
                    if loss < best_loss:
                        best_loss = loss
                        best_direction = np.array(direction)
                        best_theta = theta_val
                        best_phi = phi_val

        current_max_angle *= reduction

    cos_angle = np.clip(np.dot(best_direction, true_direction), -1.0, 1.0)
    direction_error = np.degrees(np.arccos(cos_angle))

    return {{
        'best_direction': best_direction,
        'best_theta': float(best_theta),
        'best_phi': float(best_phi),
        'best_loss': float(best_loss),
        'direction_error': direction_error
    }}


def run_stage_3_energy_scan(optimal_position, best_theta, best_phi, optimal_t0,
                             energy_guess, observed_counts, true_energy, config, prediction_simulator):
    energy_delta = config['energy_optimization']['energy_delta']
    n_steps = config['energy_optimization']['energy_scan_steps']

    energies = jnp.linspace(energy_guess - energy_delta, energy_guess + energy_delta, n_steps)

    best_loss = float('inf')
    best_energy = energy_guess
    scan_key = jax.random.PRNGKey(42)

    for energy in energies:
        track = ParticleParams(energy=energy, position=optimal_position,
                               theta=best_theta, phi=best_phi, t0=optimal_t0)
        _, _, _, total_charge = prediction_simulator(track, scan_key)
        loss = poisson_nll(observed_counts, total_charge)

        if loss < best_loss:
            best_loss = loss
            best_energy = energy

    return {{
        'best_energy': float(best_energy),
        'best_loss': float(best_loss)
    }}


def run_stage_4_adam_optimization(initial_params, observed_times, observed_counts,
                                   true_energy, true_position, true_direction, TRUE_T0,
                                   combined_grad_fn, config, detector_bounds):
    DETECTOR_R = detector_bounds['r']
    DETECTOR_H = detector_bounds['H']

    ADAM_LEARNING_RATE = config['adam_optimizer']['learning_rate']
    ADAM_B1 = config['adam_optimizer']['b1']
    ADAM_B2 = config['adam_optimizer']['b2']
    ADAM_EPS = config['adam_optimizer']['eps']
    MAX_ITERATIONS = 400
    tolerance = 1e-6

    POS_LR_SCALE = config['learning_rates']['position_learning_rate'] * 2.
    DIR_LR_SCALE = config['learning_rates']['direction_learning_rate'] * 5.
    T0_LR_SCALE = config['learning_rates']['t0_learning_rate']
    ENE_LR_SCALE = config['learning_rates']['energy_learning_rate']

    optimizer = optax.adam(learning_rate=ADAM_LEARNING_RATE, b1=ADAM_B1, b2=ADAM_B2, eps=ADAM_EPS)
    opt_state = optimizer.init(initial_params)
    current_params = jnp.array(initial_params)

    opt_key = jax.random.PRNGKey(12345)

    final_combined_loss = float('inf')
    final_sqrt_ct = float('inf')

    for iteration in range(MAX_ITERATIONS):
        opt_key, _ = jax.random.split(opt_key)

        (combined_loss, (charge_loss_val, time_loss_val, vtx_loss_val, sqrt_ct_val)), grad = combined_grad_fn(
            current_params, observed_times, observed_counts, opt_key
        )

        final_combined_loss = float(combined_loss)
        final_sqrt_ct = float(sqrt_ct_val)

        if jnp.any(jnp.isnan(grad)):
            grad = jnp.nan_to_num(grad, nan=0.0)

        grad_norm = jnp.linalg.norm(grad)
        if grad_norm < tolerance:
            break

        if iteration < 25:
            update_scales = jnp.array([0, 0, 0, 0, DIR_LR_SCALE, DIR_LR_SCALE, 0.])
        else:
            update_scales = jnp.array([
                POS_LR_SCALE, POS_LR_SCALE, POS_LR_SCALE,
                T0_LR_SCALE, DIR_LR_SCALE, DIR_LR_SCALE, ENE_LR_SCALE
            ])

        updates, opt_state = optimizer.update(grad, opt_state, current_params)
        scaled_updates = updates * update_scales
        current_params = optax.apply_updates(current_params, scaled_updates)

        current_params = jnp.array([
            jnp.clip(current_params[0], -DETECTOR_R * 0.95, DETECTOR_R * 0.95),
            jnp.clip(current_params[1], -DETECTOR_R * 0.95, DETECTOR_R * 0.95),
            jnp.clip(current_params[2], -DETECTOR_H/2 * 0.95, DETECTOR_H/2 * 0.95),
            jnp.clip(current_params[3], -20.0, 20.0),
            current_params[4],
            current_params[5],
            jnp.clip(current_params[6], 300.0, 2000.0)
        ])

    final_position = current_params[:3]
    final_t0 = current_params[3]
    final_theta = current_params[4]
    final_phi = current_params[5]
    final_energy = current_params[6]
    final_direction = spherical_to_cartesian(final_theta, final_phi)

    final_position_error = float(jnp.linalg.norm(final_position - true_position))
    final_t0_error = float(abs(final_t0 - TRUE_T0))
    final_energy_error = float(abs(final_energy - true_energy))
    cos_angle = np.clip(np.dot(np.array(final_direction), np.array(true_direction)), -1.0, 1.0)
    final_direction_error = float(np.degrees(np.arccos(cos_angle)))

    return {{
        'final_position_error': final_position_error,
        'final_direction_error': final_direction_error,
        'final_t0_error': final_t0_error,
        'final_energy_error': final_energy_error,
        'final_combined_loss': final_combined_loss,
        'final_sqrt_ct': final_sqrt_ct
    }}


def parse_args():
    parser = argparse.ArgumentParser(description='Run tau_vtx hyperparameter scan')
    parser.add_argument('--output', type=str, required=True, help='Output directory')
    parser.add_argument('--n-events', type=int, default=50, help='Events per combination')
    return parser.parse_args()


def main():
    args = parse_args()

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    n_events = args.n_events
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    csv_file = output_dir / f'tau_scan_{{timestamp}}.csv'

    total_combinations = sum(len(tau_list) for _, _, tau_list in SCAN_GRID)

    print("=" * 80)
    print("TAU_VTX HYPERPARAMETER SCAN")
    print("=" * 80)
    print(f"Started: {{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}}")
    print(f"Output: {{output_dir}}")
    print(f"CSV: {{csv_file}}")
    print(f"Events per combination: {{n_events}}")
    print(f"Total combinations: {{total_combinations}}")
    print(f"Total events: {{total_combinations * n_events}}")
    print("=" * 80)

    config = load_optimization_config(OPT_CONFIG)
    if 'optimization_params' not in config:
        config['optimization_params'] = {{}}
    config['optimization_params'].setdefault('damping_factor', 0.998)
    if 'adam_optimizer' not in config:
        config['adam_optimizer'] = {{}}
    config['adam_optimizer'].setdefault('learning_rate', 0.2)
    config['adam_optimizer'].setdefault('b1', 0.9)
    config['adam_optimizer'].setdefault('b2', 0.999)
    config['adam_optimizer'].setdefault('eps', 1e-8)

    print("Setting up detector...")
    detector = generate_detector(GEOM_CONFIG)
    detector_points = jnp.array(detector.all_points)
    NUM_DETECTORS = len(detector_points)
    detector_bounds = get_detector_bounds(detector)
    print(f"Detector: R={{detector_bounds['r']:.2f}}m, H={{detector_bounds['H']:.2f}}m, {{NUM_DETECTORS}} sensors")

    range_params = load_range_params('muon', 'water')

    csv_headers = [
        'tau_vtx', 'nrays', 'energy_MeV', 'n_events',
        'pos_err_68', 'pos_err_68_lo', 'pos_err_68_hi', 'pos_err_68_se',
        't0_err_68', 't0_err_68_lo', 't0_err_68_hi', 't0_err_68_se',
        'dir_err_68', 'dir_err_68_lo', 'dir_err_68_hi', 'dir_err_68_se',
        'E_err_68', 'E_err_68_lo', 'E_err_68_hi', 'E_err_68_se',
        'loss_combined', 'loss_sqrt_ct'
    ]

    with open(csv_file, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(csv_headers)

    bootstrap_rng = np.random.default_rng(42)

    combination_idx = 0
    current_nrays = None
    prediction_simulator = None
    data_simulator = None

    for nrays, energy_mev, tau_list in SCAN_GRID:
        if nrays != current_nrays:
            print(f"\\nSetting up simulators for Nrays={{nrays:,}}...")
            prediction_simulator = setup_event_simulator(
                GEOM_CONFIG, nrays, TEMPERATURE,
                max_sensors_per_cell=4, K=K, is_data=False,
                physics_config=PHYSICS_CONFIG, default_detector_params=True
            )
            data_simulator = setup_event_simulator(
                GEOM_CONFIG, nrays, temperature=0.0,
                K=12, is_data=True, is_calibration=False,
                physics_config=PHYSICS_CONFIG, default_detector_params=True
            )
            current_nrays = nrays

        data_dir = f"{{ENERGY_BASE_PATH}}{{energy_mev}}MeV/"
        if not os.path.exists(data_dir):
            print(f"WARNING: {{data_dir}} not found, skipping...")
            continue

        for tau_vtx in tau_list:
            combination_idx += 1
            print(f"\\n[{{combination_idx}}/{{total_combinations}}] tau={{tau_vtx}}, Nrays={{nrays:,}}, E={{energy_mev}}MeV")

            position_errors = []
            t0_errors = []
            direction_errors = []
            energy_errors = []
            combined_losses = []
            sqrt_ct_losses = []

            main_key = jax.random.PRNGKey(42 + combination_idx * 1000)
            event_keys = jax.random.split(main_key, n_events)

            successful_events = 0

            for event_idx in tqdm(range(n_events), desc="Events", leave=False):
                try:
                    event_key = event_keys[event_idx]
                    max_attempts = 10
                    endpoint_valid = False

                    for attempt in range(max_attempts):
                        event_data = generate_event_data(
                            event_idx, event_key, data_dir,
                            data_simulator, detector_bounds, detector_points, fraction=0.9
                        )
                        endpoint_valid = check_track_endpoint_in_detector(
                            event_data['true_position'],
                            event_data['true_direction'],
                            event_data['true_energy'],
                            range_params, detector_bounds, fraction=0.9
                        )
                        if endpoint_valid:
                            break
                        event_key, _ = jax.random.split(event_key)

                    if not endpoint_valid:
                        continue

                    true_position = event_data['true_position']
                    true_direction = event_data['true_direction']
                    true_energy = event_data['true_energy']
                    TRUE_T0 = event_data['TRUE_T0']

                    hit_mask = event_data['hit_counts'] > -999
                    hit_detector_positions = detector_points[hit_mask]
                    observed_times = event_data['hit_times'][hit_mask]
                    observed_counts = event_data['hit_counts'][hit_mask]
                    all_observed_times = event_data['hit_times']
                    all_observed_counts = event_data['hit_counts']

                    combined_grad_fn, _ = create_combined_loss_function(
                        prediction_simulator, NUM_DETECTORS, TAU_TIME, tau_vtx, hit_detector_positions
                    )

                    stage1 = run_stage_1_position_search(
                        hit_detector_positions, observed_times, observed_counts,
                        true_position, TRUE_T0, 0.0, detector_bounds, config
                    )
                    if stage1['best_position'] is None:
                        continue

                    stage2 = run_stage_2_direction_search(
                        stage1['best_position'], stage1['best_t0'],
                        true_energy, all_observed_counts, true_direction, config, prediction_simulator
                    )

                    stage3 = run_stage_3_energy_scan(
                        stage1['best_position'], stage2['best_theta'],
                        stage2['best_phi'], stage1['best_t0'],
                        true_energy, all_observed_counts, true_energy, config, prediction_simulator
                    )

                    initial_params = jnp.array([
                        stage1['best_position'][0], stage1['best_position'][1], stage1['best_position'][2],
                        stage1['best_t0'], stage2['best_theta'], stage2['best_phi'], stage3['best_energy']
                    ])

                    stage4 = run_stage_4_adam_optimization(
                        initial_params, all_observed_times, all_observed_counts,
                        true_energy, true_position, true_direction, TRUE_T0,
                        combined_grad_fn, config, detector_bounds
                    )

                    position_errors.append(stage4['final_position_error'])
                    t0_errors.append(stage4['final_t0_error'])
                    direction_errors.append(stage4['final_direction_error'])
                    energy_errors.append(stage4['final_energy_error'])
                    combined_losses.append(stage4['final_combined_loss'])
                    sqrt_ct_losses.append(stage4['final_sqrt_ct'])
                    successful_events += 1

                except Exception as e:
                    print(f"  Error event {{event_idx}}: {{e}}")
                    continue

            if successful_events > 0:
                pos_boot = bootstrap_percentile_ci(position_errors, rng=bootstrap_rng)
                t0_boot = bootstrap_percentile_ci(t0_errors, rng=bootstrap_rng)
                dir_boot = bootstrap_percentile_ci(direction_errors, rng=bootstrap_rng)
                E_boot = bootstrap_percentile_ci(energy_errors, rng=bootstrap_rng)

                with open(csv_file, 'a', newline='') as f:
                    writer = csv.writer(f)
                    writer.writerow([
                        tau_vtx, nrays, energy_mev, successful_events,
                        f"{{pos_boot['estimate']:.4f}}", f"{{pos_boot['ci_lower']:.4f}}",
                        f"{{pos_boot['ci_upper']:.4f}}", f"{{pos_boot['std_error']:.4f}}",
                        f"{{t0_boot['estimate']:.4f}}", f"{{t0_boot['ci_lower']:.4f}}",
                        f"{{t0_boot['ci_upper']:.4f}}", f"{{t0_boot['std_error']:.4f}}",
                        f"{{dir_boot['estimate']:.4f}}", f"{{dir_boot['ci_lower']:.4f}}",
                        f"{{dir_boot['ci_upper']:.4f}}", f"{{dir_boot['std_error']:.4f}}",
                        f"{{E_boot['estimate']:.4f}}", f"{{E_boot['ci_lower']:.4f}}",
                        f"{{E_boot['ci_upper']:.4f}}", f"{{E_boot['std_error']:.4f}}",
                        f"{{np.mean(combined_losses):.6f}}", f"{{np.mean(sqrt_ct_losses):.6f}}"
                    ])

                print(f"  {{successful_events}} events: pos_68={{pos_boot['estimate']:.3f}}m, dir_68={{dir_boot['estimate']:.2f}}deg")

    print("\\n" + "=" * 80)
    print(f"SCAN COMPLETE: {{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}}")
    print(f"Results: {{csv_file}}")
    print("=" * 80)


if __name__ == '__main__':
    main()
'''
    return run_script


def generate_slurm_script(output_dir, n_events, job_name, project_root,
                          partition='ampere', account='mli:cider-ml', time_limit='24:00:00'):
    """Generate SLURM batch script content."""

    output_path = Path(output_dir).resolve()

    # Create log directory
    log_dir = project_root / 's3df_jobs' / 'logs'
    log_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    log_file = log_dir / f'{job_name}_{timestamp}.log'
    run_script_file = project_root / 's3df_jobs' / 'generated_scripts' / f'{job_name}_run_{timestamp}.py'

    total_combinations = count_combinations()

    slurm_script = f"""#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --output={log_file}
#SBATCH --error={log_file}
#SBATCH --partition={partition}
#SBATCH --account={account}
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --gpus=1
#SBATCH --mem=39936
#SBATCH --time={time_limit}

echo "=========================================="
echo "TAU_VTX HYPERPARAMETER TUNING"
echo "=========================================="
echo "Job ID: $SLURM_JOB_ID"
echo "Node: $SLURM_NODELIST"
echo "Started: $(date)"
echo "=========================================="
echo ""

cd {project_root}
echo "Working directory: $(pwd)"

export SINGULARITY_IMAGE_PATH=/sdf/group/neutrino/images/develop.sif
function spython() {{
    singularity exec --nv -B /sdf,/fs,/sdf/scratch,/lscratch ${{SINGULARITY_IMAGE_PATH}} python "$@"
}}

echo ""
echo "GPU Information:"
singularity exec --nv -B /sdf,/fs,/sdf/scratch,/lscratch ${{SINGULARITY_IMAGE_PATH}} nvidia-smi
echo ""

echo "=========================================="
echo "Scan Parameters:"
echo "  Output: {output_path}"
echo "  Events per combination: {n_events}"
echo "  Total combinations: {total_combinations}"
echo "  Total events: {total_combinations * n_events}"
echo "=========================================="
echo ""

spython -u {run_script_file} \\
    --output {output_path} \\
    --n-events {n_events}

exit_code=$?

echo ""
echo "=========================================="
echo "Completed: $(date)"
echo "Exit code: $exit_code"
echo "=========================================="

exit $exit_code
"""

    return slurm_script, log_file, run_script_file


def main():
    """Main execution function."""
    args = parse_args()

    project_root = Path(__file__).resolve().parent.parent

    print(f"Script location: {Path(__file__).resolve()}")
    print(f"Project root: {project_root}\n")

    output_path = Path(args.output)
    output_path.mkdir(parents=True, exist_ok=True)

    # Generate scripts
    slurm_script, log_file, run_script_file = generate_slurm_script(
        args.output, args.n_events, args.job_name, project_root,
        args.partition, args.account, args.time
    )

    run_script = generate_run_script(project_root)

    # Save scripts
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    script_dir = project_root / 's3df_jobs' / 'generated_scripts'
    script_dir.mkdir(parents=True, exist_ok=True)

    slurm_file = script_dir / f'{args.job_name}_{timestamp}.sh'
    with open(slurm_file, 'w') as f:
        f.write(slurm_script)
    slurm_file.chmod(0o755)

    with open(run_script_file, 'w') as f:
        f.write(run_script)
    run_script_file.chmod(0o755)

    total_combinations = count_combinations()

    print(f"{'='*80}")
    print(f"TAU_VTX HYPERPARAMETER TUNING - SLURM Job Generated")
    print(f"{'='*80}")
    print(f"SLURM script: {slurm_file}")
    print(f"Run script: {run_script_file}")
    print(f"Output: {Path(args.output).resolve()}")
    print(f"Log file: {log_file}")
    print(f"Events per combination: {args.n_events}")
    print(f"Time limit: {args.time}")
    print()
    print(f"Scan grid: {total_combinations} combinations")
    for nrays, energy, tau_list in SCAN_GRID:
        print(f"  Nrays={nrays//1000}k, E={energy}MeV: tau={tau_list}")
    print(f"\nTotal events: {total_combinations * args.n_events}")
    print(f"{'='*80}")

    if args.submit:
        print("\nSubmitting job to SLURM...")
        try:
            result = subprocess.run(['sbatch', str(slurm_file)], check=True,
                                     stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            print(f"\n{result.stdout.decode().strip()}")
            print(f"\nMonitor with: squeue -u $USER")
            print(f"View log: tail -f {log_file}")
        except subprocess.CalledProcessError as e:
            print(f"Error submitting job: {e}")
            if e.stderr:
                print(f"STDERR: {e.stderr.decode()}")
            return 1
        except FileNotFoundError:
            print("Error: 'sbatch' command not found.")
            return 1
    else:
        print("\nTo submit this job, run:")
        print(f"  sbatch {slurm_file}")
        print("\nOr re-run with --submit flag")

    return 0


if __name__ == '__main__':
    exit(main())
